### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by drewdotpro** [zachsoft/Ionic-Material#1]
Looks great, but some API documentation would be incredible. Thanks =D

**Comment by zachsoft** [comment]
For sure. I'm looking to add the initial documentation asap.

**Comment by AntonVoltchok** [comment]
:+1:  I just started a new project and bumped into this. Got pretty hyped then realized the no docs thing. Even a little info would be awesome while waiting on the full docs.

Either way, this looks pretty badass Zach! I tried mixing Angular Material with Angular Ionic, while it sort of worked, mixing the libraries led to some pretty big problems which I didn't have time to work out, this looks like it was way more thought out then my silly experiment haha.

Keep it up man, I have no time right now, but I'd love to make some contributions when I get a chance.

**Comment by zachsoft** [comment]
@AntonVoltchok, I'll keep you posted. The current state of the project is "experimental preview" - I'm in the works to get us a release that is much closer to production ready than the current state. Thanks so much for checking this out, even at this current state of the project.

To help with testing coverage, what are some of the libraries you are using within your Ionic app?

**Comment by Purus** [comment]
My apps are in earlier stage and I guess this would be perfect time to test this with some help on docs.

**Comment by rlucian** [comment]
Initial docs could include instructions on setting up the dev env.
Also, some examples on using some of the most basic features would help imagine the rest.

**Comment by janicklas-ralph** [comment]
Having a hard time setting this up with my existing Ionic app..
Would love to see the Docs with some integration sample.. A 'how to add it to your existing ionic app' sample would be super helpful

Thank you for this great initiative!

**Comment by michaelbina** [comment]
I'm also a little lost on getting this set up.  I included the js and css files but am not sure if I'm supposed to run something to initialize the library.  I'm not seeing any changes to my app.  Any help before docs are released would be nice.  Can point to my code if needed.

**Comment by rlucian** [comment]
We switched to the "official" angular-material, which has some issues of its own, but you can manage to get it to work and has a better coverage and some support.

As soon as @zachsoft posts some updates I am willing to give it a shot again. Some realistic milestone definitions could give us some reasonable expectations on whether this will be a usable product or not, and some outlines of the planned architecture may even drive some people to contribute to the code...

Also, I don't see too much activity on the repo... so I am not very optimistic.

**Comment by michaelbina** [comment]
@rlucian - how is that working out in terms of integration with ionic?  I have another project set up that uses angular with material design for web but I was hoping this would be a nice integration with the ionic code I've already wrote.

Any word from @zachsoft would be nice...

**Comment by AntonVoltchok** [comment]
Man I wish I had more time to contribute to this. 
@rlucian @michaelbina  in my Angular mobile app I'm using a bit of Ionic, I haven't integrated material like this, I just took some javascript and CSS from Google Angular Material swapped it into an Angular mobile app, works alright if you want to try that out.

**Comment by rlucian** [comment]
sorry for continuing the hijacking of this thread, but overall i guess it's for a good cause: "using ionic with material design"

So, @michaelbina , it actually works pretty well... 
There are still some issue to be resolved in regard to the click event when using the current angular material libraries, but a fix is scheduled for the 0.9.0 release of the angularjs material project.

Until then, you need to fiddle a little with the versions, e.g. the 0.7.0 version works, but nothing above that yet. See [this thread](http://forum.ionicframework.com/t/will-googles-material-design-polymer-elements-ever-come-to-ionic/6102/21) and if you don't get it working let me know and i will share my working configuration of included libraries. 

What we do is develop on 0.7.0 and overlook the minor issues on some views, and we will simply switch to 0.9.0 once it's released.

Apart from having the configuration on the forum thread cited above, you then reference to the angularjs material project and use their md-* directives instead of the ion-* ones. Most of them are working, rest of them will probably be working once we can all switch to the 0.9.0 release, but you can certainly get a feeling of how it looks for the few days that remain until the expected release of 0.9.0.

If you want to see more, I can probably give you access to the alpha release of our app on play store. It's still rough around the edges, but you'll get the idea.

**Comment by zachsoft** [comment]
API documentation + sample app provided in latest release

**Comment by amanuel2** [comment]
Not really. I dont see it..

**Comment by KnoxArg** [comment]
Is this proyect abandoned?

**Comment by christoga** [comment]
Yeah, this project is not maintained anymore @KnoxArg

**Comment by amanuel2** [comment]
Wait what @christoga .... How did such a big project go down?

**Comment by rlucian** [comment]
Unfortunately it wasn't really that big. Read through the thread.

**Comment by christoga** [comment]
There is an issues for this topic,
Try to find it on the issues list 😉

**Comment by KnoxArg** [comment]
@christoga Thanks for your reply. Can you recommend me an alternative if I want to use material design in an Ionic V1 project?

**Comment by christoga** [comment]
In my cordova project, I use getmdl.io for the framework 👍

**Comment by amanuel2** [comment]
Thats not for mobile @christoga ...

**Comment by rlucian** [comment]
this should work: https://material.angularjs.org/latest/
although the "material design lite" should work just fine, in the end it's css and js, and that should be fine on ionic.

**Comment by KnoxArg** [comment]
Not sure MaterialJS would work

_Angular Material v1.0 has known integration issues with the following libraries:
Ionic - Open-source SDK for developing hybrid mobile apps with Web technologies has touch support that interferes with ngMaterial's mobile gesture features._

**Comment by amanuel2** [comment]
Angular Material Wont Work For Mobile. Unless your a Front-End Expert. Which im not....
