### ISSUE TITLE
[OT] relationship between ionic material and ionic + ionic 2 support

### ISSUE THREAD

**Issue by guykatz** [zachsoft/Ionic-Material#140]
Hi;
this is slightly off topic but its the only place I found I can ask questions.
I am new to angular+ionic. I have decided to go with angular 2 and ionic 2 (both of which are in alpha stage but I am not in a hurry at all). I love material design and stumble upon this great project.
my question is what is the relationship between ionic and ionic material, will there be an ionic material 2 (after ionic 2 come out) ?
thanks in advance.

**Comment by delta98** [comment]
This project hasn't had any recent activity since May. It's doubtful that any support for Ionic 2 will be available.

To answer your question, it's tightly coupled to ionic 1 components. So support for Ionic 2 would need to be developed as you said material 2.

I'd suggest this project here as a replacement for this one https://github.com/delta98/ionic-material-design-lite

**Comment by khertan** [comment]
That s not fair to promote your project this way, even if this project look like inactive.

**Comment by delta98** [comment]
How so, I answered the question and provided an alternative.

**Comment by khertan** [comment]
Indeed, do not see any offense.

**Comment by oscarmcm** [comment]
@delta98 thanks, your project looks really nice. 
@guykatz Im working on the project now :)
