### ISSUE TITLE
Demo shows blank screen

### ISSUE THREAD

**Issue by zhouhao27** [zachsoft/Ionic-Material#143]
What I did:

- cd demo
- npm install
- bower install
- ionic serve

It shows a blank screen. How to run the demo correctly? Thanks

**Comment by theborakompanioni** [comment]
This will be fixed by pull request #138.

Manually adapting the file references in index.html will fix it for now:
lib/ionic-material/ionic.material.min.css -> lib/ionic-material/**dist/**ionic.material.min.css
lib/ionic-material/ionic.material.min.js -> lib/ionic-material/**dist/**ionic.material.min.js

**Comment by zhouhao27** [comment]
Thanks. It works.

**Comment by oscarmcm** [comment]
@zhouhao27 still the problem?
