### ISSUE TITLE
[Question] Angular Material

### ISSUE THREAD

**Issue by sebrojas14** [zachsoft/Ionic-Material#15]
I read that is possible to use Ionic and Angular Material (material.angularjs.org), this project is an alternative? or is bridge between that?

**Comment by Gabriel0402** [comment]
I think that ionic use its own directives, and by using angular material, we have to use google's directive. So maybe in some cases we cannot use the angular material in ionic.

**Comment by mikehaas763** [comment]
:+1:

It's really hard to understand from the website and/or documentation what the goal is for this project. Is it going to be providing new controls/directives/components? Is it just to make the existing directives that Ionic provides align as closely as possible to material design/angular material?

It would be great if we could get a few paragraphs either in this issue, in the readme or on the website that gets in to more detail and answers these plus other questions.

**Comment by sebrojas14** [comment]
Agree @mikehaas763

**Comment by skolade** [comment]
:+1: @mikehaas763  and I am wondering why this question has not been addressed!

**Comment by raibutera** [comment]
Ionic and Angular Material are pretty incompatible (you can add them to the same project, but the styling will be extremely inconsistent and none of the UI components will work cross-framework, ie. an ionic side menu with material tabs). Ionic is 1.0 and angular material is still pre-1.0. This project is a way of implementing material design using the ionic framework.

**Comment by zachsoft** [comment]
+1 @raibutera. Ionic Material is best explained as a "material extension" to Ionic, rather than to Angular as a whole. The difference isn't just semantics - Ionic Material extends the actual ionic framework namespace (in JS), renders material styles on the ionic elements (following ionic's conventions), and will aim to follow the releases of Ionic, and support material theming, ink, and motion for any new Ionic release.

Ionic Material will pull in the best ideas of Angular Material, Paper/Polymer, etc. and by the same tune, Ionic Material will also abstract the parts of the framework that would be beneficial outside of ionic apps (like animations, motions) into their standalone git projects so they can be adopted for use in -any- web project that uses material design.

Rai, anything more on the topic? I'll string this into the docs or website so it's more clear on the distinction.

**Comment by raibutera** [comment]
I've not got anything useful to add right now.

**Comment by mikehaas763** [comment]
@zachsoft thanks for the info.

**Comment by raibutera** [comment]
Added to README
